name: Verify Changes
on: pull_request

jobs:
  verify-changes:
    runs-on: ubuntu-latest
    steps:
     - name: Change text file
       run: |
          echo "Modified" > new.txt

     - name: Change file in directory
       run: |
          echo "Changed" > test_directory/new.txt

     - name: Verify Changed files
       uses: tj-actions/verify-changed-files@eb6d385c0e52fb28e2f6b70e15c835cb3cbfff17
       id: verify-changed-files
       with:
         files: |
             *.txt
             test_directory
             action.yml
             **/*.{jpeg,py}
             !*.sql
